/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface UmSideDrawer {
    'title': string;
  }
}

declare global {


  interface HTMLUmSideDrawerElement extends Components.UmSideDrawer, HTMLStencilElement {}
  var HTMLUmSideDrawerElement: {
    prototype: HTMLUmSideDrawerElement;
    new (): HTMLUmSideDrawerElement;
  };
  interface HTMLElementTagNameMap {
    'um-side-drawer': HTMLUmSideDrawerElement;
  }
}

declare namespace LocalJSX {
  interface UmSideDrawer {
    'title'?: string;
  }

  interface IntrinsicElements {
    'um-side-drawer': UmSideDrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'um-side-drawer': LocalJSX.UmSideDrawer & JSXBase.HTMLAttributes<HTMLUmSideDrawerElement>;
    }
  }
}


